/**
 * Data access for the review app.
 *
 * Document metadata is hardcoded (the four documents of the shared
 * contract). Page-level data is read from review-site/data/<id>.json,
 * which is generated by scripts/prepare_data.py and may legitimately
 * be absent (the data directory is produced separately) — every
 * function here degrades gracefully to null / empty instead of
 * crashing.
 */
import fs from "node:fs";
import path from "node:path";

export interface DocMeta {
  id: string;
  title: string;
  subtitle: string;
  totalPages: number;
  issueFile: string;
  hasAlt: boolean;
}

export interface PageEntry {
  text: string;
  alt?: string;
  sim?: number;
  warnings?: string[];
  source?: string;
}

export interface DocData extends DocMeta {
  pages: Record<string, PageEntry>;
}

export interface DocListing extends DocMeta {
  /** true when data/<id>.json exists and parsed. */
  hasData: boolean;
  /** number of transcribed pages (0 when no data file). */
  transcribed: number;
  /** lowest transcribed page number, or 1 when no data. */
  firstPage: number;
}

export const DOCS: DocMeta[] = [
  {
    id: "140-3",
    title: "La Longue Marche — Volume 140-3",
    subtitle:
      "Handwritten manuscript — canonical reading: Gemini 3.1 Pro, prompt mateo-canonical",
    totalPages: 696,
    issueFile: "tex_output/la_longue_marche_140-3_mateo-canonical.tex",
    hasAlt: true,
  },
  {
    id: "140-4",
    title: "La Longue Marche — Volume 140-4",
    subtitle:
      "Handwritten manuscript — canonical reading: Gemini 3.1 Pro, prompt mateo-canonical",
    totalPages: 280,
    issueFile: "tex_output/la_longue_marche_140-4_mateo-canonical.tex",
    hasAlt: true,
  },
  {
    id: "preschemas",
    title: "Préschémas (Bourbaki, Schémas)",
    subtitle: "Typescript — Gemini Flash-Lite, page-by-page",
    totalPages: 437,
    issueFile: "tex_output/bourbaki_schemes_pages_flash-lite.tex",
    hasAlt: false,
  },
  {
    id: "varietes",
    title: "Catégories de variétés (U46)",
    subtitle: "Typescript with handwritten symbols — page-by-page",
    totalPages: 100,
    issueFile: "tex_output/varietes_categories_U46.tex",
    hasAlt: false,
  },
];

export function getDocMeta(id: string): DocMeta | null {
  return DOCS.find((d) => d.id === id) ?? null;
}

/**
 * Module-level cache: each lambda parses a given document file at most
 * once. Missing/broken files are NOT cached, so a data file that
 * appears later (e.g. during local dev while data prep is running)
 * gets picked up on the next request.
 */
const cache = new Map<string, DocData>();

export function loadDocData(id: string): DocData | null {
  if (getDocMeta(id) === null) return null;
  const cached = cache.get(id);
  if (cached) return cached;
  const file = path.join(process.cwd(), "data", `${id}.json`);
  try {
    const raw = fs.readFileSync(file, "utf8");
    const parsed = JSON.parse(raw) as DocData;
    if (!parsed || typeof parsed !== "object" || typeof parsed.pages !== "object") {
      return null;
    }
    cache.set(id, parsed);
    return parsed;
  } catch {
    return null;
  }
}

export function listDocs(): DocListing[] {
  return DOCS.map((meta) => {
    const data = loadDocData(meta.id);
    if (!data) {
      return { ...meta, hasData: false, transcribed: 0, firstPage: 1 };
    }
    const pageNumbers = Object.keys(data.pages)
      .map((k) => Number(k))
      .filter((n) => Number.isInteger(n) && n >= 1);
    return {
      ...meta,
      hasData: true,
      transcribed: pageNumbers.length,
      firstPage: pageNumbers.length > 0 ? Math.min(...pageNumbers) : 1,
    };
  });
}

/**
 * The transcription entry for one page, or null when the page has no
 * transcription (or the data file is missing entirely).
 */
export function getPage(docId: string, page: number): PageEntry | null {
  const data = loadDocData(docId);
  if (!data) return null;
  const entry = data.pages[String(page)];
  if (!entry || typeof entry.text !== "string") return null;
  return entry;
}
